# Import Abstract Keras Backend


In [1]:
from keras import backend as K

/home/hf/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


# Backend functions

## Check and Change Keras Backend Settings

In [2]:
K.backend()

u'tensorflow'

In [3]:
K.epsilon()

1e-07

In [4]:
K.set_epsilon('le-05')

In [5]:
K.epsilon()

'le-05'

## Convert data type

In [6]:
import numpy as np

In [7]:
a = np.array([1,1,1], dtype ='int32')
a.dtype

dtype('int32')

In [8]:
b = K.cast_to_floatx(a)
b

array([1., 1., 1.], dtype=float32)

## Numerical Operations

In [9]:
c = K.random_uniform_variable(shape=(2,3),low=0,high=1)
d = K.random_normal_variable(shape=(2,3), mean=0,scale=1)
e = K.dot(c, K.transpose(d))
e

<tf.Tensor 'MatMul:0' shape=(2, 2) dtype=float32>

In [10]:
f = K.softmax(b)
f

<tf.Tensor 'Reshape_1:0' shape=(3,) dtype=float32>

In [11]:
g = K.reshape(b, shape=(1,3))
g

<tf.Tensor 'Reshape_2:0' shape=(1, 3) dtype=float32>

## Check Keras tensor

A **'Keras tensor'** is a tensor that was returned by a Keras layer (Layer class) or by Input.

In [12]:
k_var = K.placeholder(shape=(1,1))
K.is_keras_tensor(k_var) # A variable indirectly created outside of keras is not a Keras tensor.

False

In [13]:
keras_var = K.variable(e)
K.is_keras_tensor(keras_var)  # A variable created with the keras backend is not a Keras tensor.

False

In [14]:
from keras import Input
keras_input = Input([10])
K.is_keras_tensor(keras_input) # An Input is a Keras tensor.

True

## Evaluate data

In [15]:
kvar = K.variable(np.array([[1, 2], [3, 4]]), dtype='float32')
K.eval(kvar)

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [16]:
K.count_params(kvar)

4

In [17]:
K.get_value(kvar)

array([[1., 2.],
       [3., 4.]], dtype=float32)

## Reset graph and check learning phase flag

In [18]:
K.clear_session()

In [19]:
K.learning_phase()

<tf.Tensor 'keras_learning_phase:0' shape=<unknown> dtype=bool>

Don't forget to check: https://keras.io/backend/ for more details.